### ISSUE TITLE
Duplicate results on searching by username

### ISSUE THREAD

**Issue by asdofindia** [mozilla/mozillians#2899]
If we search mozillians by (a unique name) we get only 1 result. Eg: [Akshay S Dinesh](https://mozillians.org/en-US/search/?q=Akshay+S+Dinesh)

But if we search by username, we get 2 results that are the same. Eg: [asdofindia](https://mozillians.org/en-US/search/?q=asdofindia)

**Comment by asdofindia** [comment]
This bug occurs only when the person who is searching is logged in.

**Comment by asdofindia** [comment]
This bug occurs only for confirmed profiles (not for pending profiles)

**Comment by midhmanohar** [comment]
Only one result in both [1](https://mozillians.org/en-US/search/?q=asdofindia)  [2](https://mozillians.org/en-US/search/?q=Akshay+S+Dinesh)

**Comment by asdofindia** [comment]
Try logging in.

![screenshot_firefox_20181110-163439](https://user-images.githubusercontent.com/945777/48300624-d278c880-e4d8-11e8-92c7-2f7b5a07e706.png)
![screenshot_firefox_20181110-163555](https://user-images.githubusercontent.com/945777/48300631-ea504c80-e4d8-11e8-9553-43d81f610fe9.png)

**Comment by anushbmx** [comment]
@asdofindia you are correct, there is duplicate results. The problem is Search is performed on multiple models mainly ``UserProfile, IdpProfile`` which has redundant data of user's username and email, thats why username yields duplicate not name.

when logged in user searches the Search form looks up Elastic Search index of all models and when user is not logged in search is restricted to search_models = [UserProfile, IdpProfile]

```
if profile and profile.is_vouched:
            # If this is empty, it will default to all models.
            search_models = self.get_models()
        else:
            # Anonymous and un-vouched users cannot search groups
            search_models = [UserProfile, IdpProfile]
```

https://github.com/mozilla/mozillians/blob/master/mozillians/phonebook/forms.py#L508

But that does not mean a non logged in user search does not bring duplicate results, it does but the additional privacy filter https://github.com/mozilla/mozillians/blob/master/mozillians/phonebook/forms.py#L537 which check for users privacy settings is what removes the duplicate.

Solution will be add a filter at end of ``PhonebookSearchForm`` to filter for duplicates in result.
